**Задание на повторение материала
1)Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.array([i for i in range(12, 24)])
print(a)


[12 13 14 15 16 17 18 19 20 21 22 23]


2)Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
b = a.reshape(2,6)
c = b /2
d = b *2
e = d - c
r = b + e




array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

3)Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [13]:
v = a.reshape(6,-1)
q = a.reshape(4,-1)
z = a.reshape(3,-1)
vv = a.reshape(-1,3)
qq = a.reshape(-1,4)
qq

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

4)Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [20]:
arr = np.array([[12],
       [16],
       [20],
       [21]])
#arr.ndim # показывает 2, значит двумерный

ar = np.array([1,2,3,4,5,5])
ar.ndim # показывает 1, значит одномерный

1

5)Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив. 

In [26]:
c = np.linspace(2, 3, 10)
c.size

d = c.flatten()
d.size

10

6)Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [28]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7)Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [31]:
b = np.arange(20,1,-2)
b.reshape(1,10)
# a - одномерный, b - двумерный

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

8)Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10. 

In [38]:
A = np.array([[0], 
              [0], 
              [0]])

B = np.array([[1], 
              [1]])

v = np.vstack((A, B))
v

array([[0],
       [0],
       [0],
       [1],
       [1]])

9)Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

In [47]:
a = np.arange(0,12)
A = a.reshape(4,3)

# Транспонированной матрицей_ называется матрица $A^\top$, полученная "отражением" матрицы $A$ относительно 
# её главной диагонали

At = np.transpose(A)
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

10)Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [49]:
B.size
np.linalg.det(B)
# обратную матрицу можно посчитать только для матрицы, определитель которой не равен $0$

0.0

11)Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [51]:
seed = 42
a = np.random.randint(0, seed, 10)
a

array([18, 17, 36, 23, 40, 10, 22, 38, 15, 22])

12)Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [53]:
# задание непонятно

13)Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

14)Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.